#import "../ui/Image.gql"

fragment BlogSection on BlogSectionEntityResponse {
  data {
    attributes {
      label
      title
      description
      items {
        id
        title
        href
        image {
          ...UiImage
        }
      }
    }
  }
}
