#import "../ui/Icon.gql"

fragment PricingFeaturesSection on PricingFeaturesSectionEntityResponse {
  data {
    attributes {
      label
      title
      items {
        title
        description
        icon {
          ...UiIcon
        }
      }
    }
  }
}
