#import "../ui/Icon.gql"
#import "../ui/ListItem.gql"
#import "../ui/Image.gql"

fragment PricingHeroSection on PricingHeroSectionEntityResponse {
  data {
    attributes {
      title
      description
      pricing_variant_sections {
        data {
          id
          attributes {
            title
            description
            icon {
              ...UiIcon
            }
            pricing_plans {
              data {
                id
                attributes {
                  name
                  price
                  installation
                  type
                  list {
                    ...UiListItem
                  }
                  image {
                    ...UiImage
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
