#import "../ui/Image.gql"

fragment StepsSection on StepsSectionEntityResponse {
  data {
    attributes {
      title
      description
      items {
        id
        title
        description
        image {
          ...UiImage
        }
      }
    }
  }
}
