#import "../ui/Button.gql"

fragment TipsSection on TipsSectionEntityResponse {
  data {
    attributes {
      title
      button {
        ...UiButton
      }
      items {
        id
        title
        description
        icon {
          name
        }
      }
    }
  }
}
