#import "../fragments/shared/Seo.gql"

query GetContactsPage {
  contactsPage {
    data {
      attributes {
        title
        footnote
        interest {
          id
          text
        }

        seo {
          ...SharedSeo
        }
      }
    }
  }
}
