#import "../fragments/sections/Services.gql"
#import "../fragments/sections/HomeHero.gql"
#import "../fragments/sections/Blog.gql"
#import "../fragments/sections/Steps.gql"
#import "../fragments/shared/Seo.gql"

query GetHomePage {
  homePage {
    data {
      attributes {
        home_hero_section {
          ...HomeHeroSection
        }

        services_section {
          ...ServicesSection
        }

        blog_section {
          ...BlogSection
        }

        steps_section {
          ...StepsSection
        }

        seo {
          ...SharedSeo
        }
      }
    }
  }
}
