#import "../fragments/templates/PricingPage.gql"

query GetHomeFiltrationPricePage {
  whFiltrationPrice {
    data {
      attributes {
        pricing_page_template {
          ...PricingPageTemplate
        }
      }
    }
  }
}
