#import "../fragments/templates/PricingPage.gql"
#import "../fragments/shared/Seo.gql"

query GetHomeFiltrationPricePage {
  whFiltrationPrice {
    data {
      attributes {
        pricing_page_template {
          ...PricingPageTemplate
        }

        seo {
          ...SharedSeo
        }
      }
    }
  }
}
