#import "../fragments/sections/InnerHero.gql"
#import "../fragments/sections/Content.gql"
#import "../fragments/sections/Blog.gql"
#import "../fragments/sections/Tips.gql"
#import "../fragments/shared/Seo.gql"

query GetLeakDetectionPage {
  leakDetection {
    data {
      attributes {
        inner_hero_section {
          ...InnerHeroSection
        }

        content_section {
          ...ContentSection
        }

        blog_section {
          ...BlogSection
        }

        tips_section {
          ...TipsSection
        }

        seo {
          ...SharedSeo
        }
      }
    }
  }
}
