#import "../fragments/sections/InnerHero.gql"
#import "../fragments/sections/Content.gql"
#import "../fragments/sections/Blog.gql"
#import "../fragments/sections/InnerFeatures.gql"
#import "../fragments/shared/Seo.gql"

query GetReverseOsmosisPage {
  reverseOsmosis {
    data {
      attributes {
        inner_hero_section {
          ...InnerHeroSection
        }

        content_section {
          ...ContentSection
        }

        blog_section {
          ...BlogSection
        }

        inner_features_section {
          ...InnerFeaturesSection
        }

        seo {
          ...SharedSeo
        }
      }
    }
  }
}
